export interface Machine {
  id: string;
  name: string;
  productionLine: string;
  protocol: 'OPC-UA' | 'MQTT' | 'Modbus' | 'REST' | 'CSV';
  status: 'online' | 'warning' | 'critical' | 'offline';
  riskScore: number; // 0-100
  lastMaintenanceDate: string;
  nextScheduledDate: string;
  mtbf: number; // hours
  openWorkOrders: number;
  agentId: string;
}

export interface MaintenanceTask {
  id: string;
  machineId: string;
  machineName: string;
  title: string;
  description: string;
  aiReason: string; // generated by machine agent
  priority: 'critical' | 'high' | 'medium' | 'low';
  status: 'pending' | 'in_progress' | 'completed';
  dueDate: string;
  assignedTo: string;
  estimatedHours: number;
  createdAt: string;
}

export interface TelemetryPoint {
  timestamp: string;
  temperature: number;
  vibration: number;
  pressure: number;
  rpm: number;
}

export interface Alert {
  id: string;
  machineId: string;
  machineName: string;
  severity: 'critical' | 'warning' | 'info';
  title: string;
  description: string;
  aiAnalysis: string;
  status: 'new' | 'acknowledged' | 'resolved';
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
  agentType?: 'Machine Agent' | 'Orchestrator';
}
